# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replicacao.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'replicacao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10replicacao.proto\x12\nreplicacao\"\x18\n\x04\x44\x61\x64o\x12\x10\n\x08\x63onteudo\x18\x01 \x01(\t\"\x19\n\x08\x43onsulta\x12\r\n\x05\x63have\x18\x01 \x01(\t\".\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\t\";\n\x08LogEntry\x12\r\n\x05\x65poca\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\".\n\rCommitRequest\x12\r\n\x05\x65poca\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"(\n\x03\x41\x63k\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\".\n\rEstadoReplica\x12\r\n\x05\x65poca\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"A\n\x17\x45ntradasParaSincronizar\x12&\n\x08\x65ntradas\x18\x01 \x03(\x0b\x32\x14.replicacao.LogEntry2\x7f\n\x0e\x43lienteService\x12\x34\n\nEnviarDado\x12\x10.replicacao.Dado\x1a\x14.replicacao.Resposta\x12\x37\n\tConsultar\x12\x14.replicacao.Consulta\x1a\x14.replicacao.Resposta2\xde\x01\n\x0fServidorService\x12\x38\n\x0fReplicarEntrada\x12\x14.replicacao.LogEntry\x1a\x0f.replicacao.Ack\x12;\n\rCommitEntrada\x12\x19.replicacao.CommitRequest\x1a\x0f.replicacao.Ack\x12T\n\x12SincronizarReplica\x12\x19.replicacao.EstadoReplica\x1a#.replicacao.EntradasParaSincronizarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replicacao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADO']._serialized_start=32
  _globals['_DADO']._serialized_end=56
  _globals['_CONSULTA']._serialized_start=58
  _globals['_CONSULTA']._serialized_end=83
  _globals['_RESPOSTA']._serialized_start=85
  _globals['_RESPOSTA']._serialized_end=131
  _globals['_LOGENTRY']._serialized_start=133
  _globals['_LOGENTRY']._serialized_end=192
  _globals['_COMMITREQUEST']._serialized_start=194
  _globals['_COMMITREQUEST']._serialized_end=240
  _globals['_ACK']._serialized_start=242
  _globals['_ACK']._serialized_end=282
  _globals['_ESTADOREPLICA']._serialized_start=284
  _globals['_ESTADOREPLICA']._serialized_end=330
  _globals['_ENTRADASPARASINCRONIZAR']._serialized_start=332
  _globals['_ENTRADASPARASINCRONIZAR']._serialized_end=397
  _globals['_CLIENTESERVICE']._serialized_start=399
  _globals['_CLIENTESERVICE']._serialized_end=526
  _globals['_SERVIDORSERVICE']._serialized_start=529
  _globals['_SERVIDORSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
